build:
  version: "1.0"

cards:
  message: "Welcome to my DemoAPP related QA APIs"
  contactDetails:
    name: "littleKil - Product OWNER"
    email: "littleKil@gmail.com"
  onCallSupport:
    -0987654321